branch-defaults:
  fix/aws-eb-deploy:
    environment: null
    group_suffix: null
  master:
    environment: MyApp-env
global:
  application_name: MyApp
  default_ec2_keyname: PristineUser
  default_platform: Node.js
  default_region: us-west-2
  sc: git
